Generalize  replace_groups to wide class cases
SergeyShk/Word-to-Number-Russian pull request #2
Opened 2021-04-13 08:07 UTC by ixomaxip

Made some refactoring and add function replace_groups2 to convert cases like this:
"двести пятьдесят шесть ноль два сто пять" -> 256 0 2 105

2021-04-17 05:25 UTC, SergeyShk commented on extractor.py
> +        Replaces numerical in text without grouping
Просьба убрать перевод на английский.

2021-04-17 05:29 UTC, SergeyShk requested changes
Спасибо за доработку!
Просьба убрать перевод комментариев на английский.
Также просьба дать методу replace_groups2 более осмысленное название.

2021-04-17 19:06 UTC, ixomaxip commented
Хорошо, поправлю. Только насчёт названия не уверен. Есть идеи?

2021-04-18 17:21 UTC, SergeyShk commented
replace_groups_sa (Stand-alone), например.

2021-04-19 04:43 UTC, ixomaxip commented
Спасибо! Так и сделаю

2021-04-19 04:57 UTC, ixomaxip reviewed
Поправил по замечаниям

2021-04-20 10:35 UTC, merged

2021-04-20 10:39 UTC, SergeyShk commented
Новый алгоритм не проходит по тестам (test.py), просьба посмотреть.

2021-04-21 06:55 UTC, ixomaxip commented
> Новый алгоритм не проходит по тестам (test.py), просьба посмотреть.


Проверил на коде из test.py, для replace_groups и replace_groups_sa тесты проходят. Для replace - не проходят, но я её и не менял. Запускал `pytest -s test.py`.
Вот результаты:
![image](https://user-images.githubusercontent.com/38070796/115509355-c394c380-a297-11eb-827a-8c42e0ee109e.png)
![image](https://user-images.githubusercontent.com/38070796/115509476-ea52fa00-a297-11eb-986e-89f0f6d36e61.png)

В test.py  добавил вывод имени функции тут:
```
@pytest.mark.parametrize('test', tests)
def test_extractor(extractor, test):
    text, etalon = test
    f = extractor.replace_groups
    print(f'testing function: {f.__name__}')
    guess = f(text)
    assert guess == etalon
```